### PR TITLE
Add elements.txt in favor of elements.json (Closes #3)

### LINKED ISSUE #3: use a minified json file
Instead of using a bloated fully functional json, we can use a minified json file and use `json.loads()`

### PR DESCRIPTION
**Pull request by umesh-timalsina**

### CODE REVIEW

**Comment by rsdefever** [comment]
This definitely makes the JSON more compact...but does it sacrifice readability? I guess I'm just pondering aloud whether its worth making it more compact. Thoughts?

**Comment by umesh-timalsina** [comment]
Normally this file (in a pip/conda installed setting) will be in `path/to/site-packages/element/element/lib/elements.txt`. So, I would argue that this file need not be readable.

As an example, unyt package uses the following [json](https://github.com/yt-project/unyt/blob/master/unyt/tests/data/old_json_registry.txt) for testing. 

The question I have is will this file need to be updated in future?

**Comment by rsdefever** [comment]
@umesh-timalsina upon further thinking I agree.

This file may need to be updated in the future. I certainly want to find a reliable source for these values (e.g., NIST) and scrape the data from there. I don't know where these values came from originally, and it would be worthwhile to find a reliable source and document it. 

E.g., [here](https://physics.nist.gov/cgi-bin/Compositions/stand_alone.pl?ele=&all=all&ascii=ascii&isotype=some) (or [here](https://www.nist.gov/pml/atomic-weights-and-isotopic-compositions-relative-atomic-masses) for the page used to generate the table).

**Comment by rsdefever** [comment]
Closing PR. See #3 for explanation.

**Pull request closed without merging**
